<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        
        <?php if (isset($this->metaLink)) { ?>
            <?php foreach ($this->metaLink as $meta) { ?>
                <meta property="<?php echo $meta['property']; ?>" content="<?php echo $meta['content']; ?>">
            <?php } ?>
        <?php } ?>


        <link rel="icon" href="<?php echo $this->basePath('/img/title-favicon.png?v='); ?>" type="image/x-icon">
        <title>Akila portfolio</title>
        <link href="<?php echo $this->basePath('/plugin/bootstrap-4.6/icon/bootstrap-icons.css'); ?>" rel="stylesheet" type="text/css" />
        <link href="<?php echo $this->basePath('/plugin/bootstrap-4.6/css/bootstrap.min.css'); ?>" rel="stylesheet" type="text/css" />
        <link href="<?php echo $this->basePath('/plugin/bootstrap-4.6/date_picker/bootstrap-datepicker.min.css'); ?>" rel="stylesheet" type="text/css" />
        
        
        <link href="<?php echo $this->basePath('/css/workstation.css?v='); ?>" rel="stylesheet" type="text/css" />
        <link href="<?php echo $this->basePath('/css/mobile.css?v='); ?>" rel="stylesheet" type="text/css" />

        <?php echo $this->headLink(); ?>

        <script src="<?php echo $this->basePath('/plugin/jquery/jquery.min.js'); ?>" type="text/javascript"></script>
        <script src="<?php echo $this->basePath('/plugin/bootstrap-4.6/js/bootstrap.min.js'); ?>" type="text/javascript"></script>
        <script src="<?php echo $this->basePath('/plugin/bootstrap-4.6/date_picker/bootstrap-datepicker.min.js'); ?>" type="text/javascript"></script>
        <script src="<?php echo $this->basePath('/plugin/bootstrap-4.6/js/moment.min.js'); ?>" type="text/javascript"></script>
        <script src="<?php echo $this->basePath('/plugin/bootstrap-notify/js/bootstrap-notify.min.js'); ?>" type="text/javascript"></script>
        <?php echo $this->headScript(); ?>
    </head>
    <body data-aos-easing="ease-in-out" data-aos-duration="1000" data-aos-delay="0">
        <nav class="navbar navbar-expand-lg l-nav">
            <div class="container-fluid px-0">
                <button class="navbar-toggler btn btn-sm btn-outline-light" type="button" data-toggle="collapse" data-target="#navbarToggler" aria-controls="navbarToggler" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"><i class="bi bi-list"></i></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarToggler">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item">
                            <a class="nav-link" href="#about">About</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#journey">Journey</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#skills">Skills</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#contact">Contact</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        <div class="container-fluid lcontent">
            <?php echo $this->content; ?>
        </div>
        <footer>
            <div class="container-fluid px-0">
                <div class="l-footer">
                    <span class="lftcopy">Copyright © 2024 by Akila Lakshan Weerathnga | All rights reserve</span>
                </div>
            </div>
        </footer>
    </body>
</html>