<div class="main-banner">
    <div class="row align-items-between">
        <div class="col-12 col-sm-4 text-right show-mob">
            <img src="<?php echo $this->basePath('/img/banner-bg.jpg'); ?>" type="image/x-icon" alt="Akila's banner" class="l-banner-img" >
        </div>
        <div class="col-12 col-sm-8 l-text-light l-banner">
            <p class="l-banner-text h1 mb-3">Hi I'm Akila Lakshan Weerathunga</p>
            <div class="l-subtext mb-3">
                <span class="l-text first-text">I'm a</span>
                <span class="l-text sec-text">UI Developer (Web,Mobile,GUI)</span>
            </div>
            <p class="l-banner-sub mb-5">a passionate Frontend Software Engineer with a year of     professional experience and a dedication to crafting exceptional user interfaces. Currently     pursuing my BSE (Hons) in Software Engineering, I thrive on turning ideas into intuitive and visually appealing digital experiences.</p>
            <a href="akila.pdf" class="btn btn-outline-info" target="_blank">Download CV</a>
            <a href="tel:+94771004153" class="btn btn-outline-info">Let's Talk</a>
            <div class="d-flex mt-5">
                <a href="https://wa.me/+94760192959" class="btn btn-outline-info mr-2 rounded-circle" target="_blank"><i class="bi bi-whatsapp" ></i></a>
                <a href="https://web.facebook.com/akilalweerathunga" class="btn btn-outline-info mr-2 rounded-circle" target="_blank"><i class="bi bi-facebook" ></i></a>
                <!-- <a href="https://www.linkedin.com/in/akila-lakshan-weerathunga-64b7861b9/" class="btn btn-outline-info mr-2 rounded-circle" target="_blank"><i class="bi bi-linkedin"></i></a> -->
            </div>
        </div>
        <div class="col-12 col-sm-4 text-right hide-mob">
            <img src="<?php echo $this->basePath('/img/banner-bg.jpg'); ?>" type="image/x-icon" alt="Akila's banner" class="l-banner-img" >
        </div>
    </div>
</div>
<div class="about-me mb-5" id="about">
    <div class="row justify-content-center">
        <div class="col-8 text-center">
            <p class="l-title">About <span class="l-title-sec">Me</span></p>
            <div class="l-about-img-wrapper">
                <img  src="<?php echo $this->basePath('/img/about-bg.png'); ?>" type="image/x-icon" alt="Akila's banner" class="l-about-img"/>
            </div>
            <p class="l-sub-title">Frontend Developer!</p>
            <p>Hello, I'm Akila Lakshan Weerathnga, a passionate Frontend Software Engineer with a year of professional experience and a dedication to crafting exceptional user interfaces. Currently pursuing my BSE (Hons) in Software Engineering, I thrive on turning ideas into intuitive and visually appealing digital experiences.</p>
            <div class="read-more d-none">
                <p class="l-sub-title">Professional Expertise</p>
                <p>My expertise lies in creating seamless and responsive user interfaces across various platforms. From Mobile Applications to Web and Software UI, I combine technical proficiency with a keen eye for UI/UX design. My goal is to not just meet the functional requirements but to elevate the overall user experience.</p>

                <p class="l-sub-title">Skills</p>
                <p>Mobile Application UI: Designing captivating interfaces for mobile platforms that prioritize user experience and functionality.
                Web UI: Crafting visually appealing and responsive web interfaces that enhance user engagement.
                Software UI with UI/UX: Bringing software applications to life through well-thought-out user interfaces, ensuring a smooth and enjoyable user journey.</p>
                <p class="l-sub-title">Educational Background</p>
                <p>I am currently pursuing my Bachelor's degree in Software Engineering, where I continue to deepen my understanding of software development principles and practices. My academic journey complements my hands-on experience, providing a well-rounded foundation for tackling complex frontend challenges.</p>

                <p class="l-sub-title">Approach to Work</p>
                <p>I approach every project with a blend of creativity and precision. I believe in the power of collaboration and continuous learning, always seeking to stay updated with the latest industry trends and design methodologies.</p>

                <p class="l-sub-title">Let's Connect</p>
                <p>I am enthusiastic about connecting with fellow developers, designers, and industry professionals. Whether you have a project in mind or want to discuss the latest advancements in frontend development, I'm always open to new opportunities and collaborations.</p>

                <p>Thank you for visiting my portfolio, and I look forward to the possibility of working together to create exceptional digital experiences.</p>


            </div>
            <a id="toggle-btn" class="btn btn-info mb-3">Read More</a>
        </div>
    </div>
</div>
<div class="journey mb-5" id="journey">
    <p class="l-title text-center">My <span class="l-title-sec">Journey</span></p>
    <div class="row justify-content-center">
        <div class="col-12 col-sm-11">
            <div class="row justify-content-center">
                <div class="col-12 col-sm-6">
                    <p>Education</p>
                    <div class="card l-excard">
                        <div class="card-body">
                            <p class="small l-time">2020-Present</p>
                            <p class="mb-0">undergraduate BSE(Hons).Software Engineering</p>
                            <p class="small">The Open University Sri Lanka</p>
                        </div>
                    </div>
                </div>
                <div class="col-12 col-sm-6">
                    <p>Experience</p>
                    <div class="card l-excard">
                        <div class="card-body">
                            <p class="small l-time">2023-Present</p>
                            <p class="mb-0">Trainee UI Developer</p>
                            <p class="small">Portion (pvt) Ltd.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="skills mb-5 pb-3" id="skills">
    <p class="l-title text-center">My <span class="l-title-sec">Skills</span></p>
    <div class="row justify-content-center">
        <div class="col-12 col-sm-11">
            <div class="row justify-content-center">
                <div class="col-12 col-sm-6">
                    <p>Coding Skills</p>
                    <div class="card l-excard">
                        <div class="card-body">
                            <div class="l-progress_bar block">
                                <div class="progress_bar">
                                    <div class="progress_bar_item mt-2">
                                        <div class="d-flex">
                                            <div class="item_label cell auto">HTML</div>
                                            <div class="item_value cell shrink ml-auto">0%</div>
                                        </div>
                                        <div class="item_bar cell"><div class="progress" data-progress="90"></div></div>
                                    </div>
                                    <div class="progress_bar_item mt-2">
                                        <div class="d-flex">
                                            <div class="item_label cell auto">CSS</div>
                                            <div class="item_value cell shrink ml-auto">0%</div>
                                        </div>
                                        <div class="item_bar cell"><div class="progress" data-progress="85"></div></div>
                                    </div>
                                    <div class="progress_bar_item mt-2">
                                        <div class="d-flex">
                                            <div class="item_label cell auto">Javascript</div>
                                            <div class="item_value cell shrink ml-auto">0%</div>
                                        </div>
                                        <div class="item_bar cell"><div class="progress" data-progress="70"></div></div>
                                    </div>
                                    <div class="progress_bar_item mt-2">
                                        <div class="d-flex">
                                            <div class="item_label cell auto">Android</div>
                                            <div class="item_value cell shrink ml-auto">0%</div>
                                        </div>
                                        <div class="item_bar cell"><div class="progress" data-progress="70"></div></div>
                                    </div>
                                    <div class="progress_bar_item mt-2">
                                        <div class="d-flex">
                                            <div class="item_label cell auto">C#</div>
                                            <div class="item_value cell shrink ml-auto">0%</div>
                                        </div>
                                        <div class="item_bar cell"><div class="progress" data-progress="50"></div></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-12 col-sm-6">
                    <p>Professional Skills</p>
                    <div class="card l-excard">
                        <div class="card-body">
                            <div class="l-progress_bar block">
                                <div class="progress_bar">
                                    <div class="progress_bar_item mt-2">
                                        <div class="d-flex">
                                            <div class="item_label cell auto">Web Design UI</div>
                                            <div class="item_value cell shrink ml-auto">0%</div>
                                        </div>
                                        <div class="item_bar cell"><div class="progress" data-progress="95"></div></div>
                                    </div>
                                    <div class="progress_bar_item mt-2">
                                        <div class="d-flex">
                                            <div class="item_label cell auto">Web Application UI</div>
                                            <div class="item_value cell shrink ml-auto">0%</div>
                                        </div>
                                        <div class="item_bar cell"><div class="progress" data-progress="90"></div></div>
                                    </div>
                                    <div class="progress_bar_item mt-2">
                                        <div class="d-flex">
                                            <div class="item_label cell auto">Mobile Application UI</div>
                                            <div class="item_value cell shrink ml-auto">0%</div>
                                        </div>
                                        <div class="item_bar cell"><div class="progress" data-progress="70"></div></div>
                                    </div>
                                    <div class="progress_bar_item mt-2">
                                        <div class="d-flex">
                                            <div class="item_label cell auto">Boostrap</div>
                                            <div class="item_value cell shrink ml-auto">0%</div>
                                        </div>
                                        <div class="item_bar cell"><div class="progress" data-progress="85"></div></div>
                                    </div>
                                    <div class="progress_bar_item mt-2">
                                        <div class="d-flex">
                                            <div class="item_label cell auto">PHP Frameworks(Laminas,Zend,Laravel)</div>
                                            <div class="item_value cell shrink ml-auto">0%</div>
                                        </div>
                                        <div class="item_bar cell"><div class="progress" data-progress="80"></div></div>
                                    </div>
                                    <div class="progress_bar_item mt-2">
                                        <div class="d-flex">
                                            <div class="item_label cell auto">React, Angular</div>
                                            <div class="item_value cell shrink ml-auto">0%</div>
                                        </div>
                                        <div class="item_bar cell"><div class="progress" data-progress="80"></div></div>
                                    </div>
                                    <div class="progress_bar_item mt-2">
                                        <div class="d-flex">
                                            <div class="item_label cell auto">C#,JavaFX UI</div>
                                            <div class="item_value cell shrink ml-auto">0%</div>
                                        </div>
                                        <div class="item_bar cell"><div class="progress" data-progress="50"></div></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="contact mb-5" id="contact">
    <div class="row justify-content-center">
        <div class="col-12 col-sm-8 text-center">
            <p class="l-title">Contact <span class="l-title-sec">Me</span></p>
            <p><i class="bi bi-geo-alt-fill mr-2"></i> No. 103, New Peradeniya, Karamada, Gelioya, Sri Lanka</p>
            <p><i class="bi bi-telephone-fill mr-2"></i> +94 77 100 4153 or <a href="tel:+94771004153">Call Now</a></p>
            <p><i class="bi bi-telephone-fill mr-2"></i> +94 76 019 2959 or <a href="tel:+94760192959">Call Now</a></p>
            <p><i class="bi bi-envelope-at-fill mr-2"></i> wbakilalakshan@gmail.com or <a href="mailto:wbakilalakshan@gmail.com">Send Mail</a></p>  
        </div>
    </div>
</div>

<script>
        $(document).ready(function(){
            progress_bar();

            $("#toggle-btn").on("click", function () {
                $(".read-more").toggleClass("d-none");

                var buttonText = $(".read-more").hasClass("d-none") ? "Read More" : "Read Less";
                $("#toggle-btn").text(buttonText);
            });
        });

        function progress_bar() {
            var speed = 30;
            var items = $('.progress_bar').find('.progress_bar_item');
            
            items.each(function() {
                var item = $(this).find('.progress');
                var itemValue = item.data('progress');
                var i = 0;
                var value = $(this);
                
                var count = setInterval(function(){
                    if(i <= itemValue) {
                        var iStr = i.toString();
                        item.css({
                            'width': iStr+'%'
                        });
                        value.find('.item_value').html(iStr +'%');
                    }
                    else {
                        clearInterval(count);
                    }
                    i++;
                },speed);
            });
        }
    </script>